config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks
  resources :users, only: [:new, :create, :show]
  root to: 'tasks#index'
  namespace :admin do
      resources :users, only: [:index, :show, :new, :create, :destroy, :edit, :update]
      resources :tags
      end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :tasks, through: :taggings

  validates :name, presence: true
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :task
  belongs_to :tag
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :deadline, presence: true
  validates :status, presence: true
  validates :priority, presence: true

  enum status: { 未着手: 0, 着手中: 1, 完了: 2 }
  enum priority: { 低: 0, 中: 1, 高: 2 }
  
  scope :search_by_task_title, -> (search){where('title like ?', "%#{search}%" )}
  scope :search_by_status, -> status { where(status: status) }
  scope :search_tag, -> (data){ joins(:tags).where('tags.id = ?', data)}


  max_paginates_per 5
  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :tasks, dependent: :destroy
  max_paginates_per 5
  before_destroy :ensure_admin_deatroy
  before_update :ensure_admin_update

  private

  def ensure_admin_deatroy
     throw(:abort) if User.where(admin: true).count <= 1 && self.admin == true
   end

  def ensure_admin_update
      if User.where(admin: true).count == 1 && self.admin == false
        errors.add(:admin,"は、最低でも１人は必要です。")
        throw(:abort)
      end
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
#  before_action :check_login
  before_action :require_admin

  def new
    @tag = Tag.new
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to new_admin_tag_path
    else
      render :new
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    if @tag.destroy
      redirect_to new_admin_tag_path, notice:"#{@tag.name}ラベルを削除しました"
    else
      render :new
    end
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end

  def require_admin
    unless current_user.admin?
    redirect_to tasks_path
    flash[:notice] = '管理者以外はアクセスを許可されていません'
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy, :show]
  before_action :require_admin


  def index
    @users = User.all.includes(:tasks)
  end

  def new
    @user = User.new
  end

  def show

  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "#{@user.name}を登録しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), notice: 'ユーザー情報を変更しました'
    else
      render :edit, notice: "更新に失敗しました"
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "#{@user.name}さん関連のデータを削除しました"
    else
      redirect_to admin_users_path, notice: "管理権限者は、最低でも１人は必要です。"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin, :show)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_admin
    if current_user.nil? || !current_user.admin?
      redirect_to tasks_path, notice: "管理者以外はアクセスできません。"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private
 def login_required
   redirect_to new_session_path unless current_user
 end
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    unless logged_in?
       @user = User.new
    else
      redirect_to root_path, notice: 'すでにログインしています。'
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
   before_action :set_task, only: [:show, :edit, :update, :destroy]
   before_action :login_require

  def index

    @tasks = current_user.tasks
    #@tasks = @tasks.includes(:current_user)



    if params[:sort_expired]
      @tasks = @tasks.order(deadline: :desc).page(params[:page]).per(20)
    elsif params[:sort_priority]
      @tasks = @tasks.order(priority: :desc).page(params[:page]).per(20)
    else
      @tasks = @tasks.order(created_at: :desc).page(params[:page]).per(20)
    end

    if params[:task].present?
      if params[:title].present? && params[:task][:status].present?
        @tasks = @tasks.where('title LIKE ?', "%#{params[:task][:title]}%").page(params[:page]).per(20)
        @tasks = @tasks.where(status: params[:task][:status]).page(params[:page]).per(20)

      elsif params[:task][:title].present?
        @tasks = @tasks.where('title LIKE ?', "%#{params[:task][:title]}%").page(params[:page]).per(20)

      elsif params[:task][:status].present?
        @tasks = @tasks.where(status: params[:task][:status]).page(params[:page]).per(20)

      elsif params[:task][:tag].present?
      @tasks = current_user.tasks.search_tag(params[:task][:tag]).page(params[:page]).per(20)
      else
        @tasks = current_user.tasks.select(:id, :title, :content, :created_at,:status,:priority,:deadline).order(created_at: :DESC).page(params[:page]).per(20)
      end

    end



end

  def new
    @task = Task.new
  end

  def show
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path, notice: "タスクを作成しました！"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
     redirect_to tasks_path, notice:"タスクを削除しました！"
  end

  private
    def task_params
      params.require(:task).permit(:title, :content, :deadline, :status, :priority,{ tag_ids: [] } )
    end

    def set_task
      @task = Task.find(params[:id])
    end

    def login_require
    redirect_to new_session_path unless current_user
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :check_user, only: [:edit, :update]
  def new
     @user = User.new
     redirect_to user_path(current_user.id) if logged_in?
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = current_user
    redirect_to tasks_path if @user.id !=  params[:id].to_i
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation,:admin)
  end

  def check_user
    @user = User.find(params[:id])
    unless current_user.id == @user.id
      flash[:notice] = "編集権限がありません"
      redirect_to tasks_path
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/tags/new.html.erb
<h2>ラベル作成</h2>
<div class="main-area">
  <div class="card p-3">
    <%= form_with(model: @tag, url: admin_tags_path,local:true,class:"row g-3") do |f| %>
    <div class="col-auto">
      <%= f.label :name,'ラベル名' ,class:"form-label"%>
    </div>
    <div class="col-auto">
      <%= f.text_field :name , class:"form-control form-control-sm"%>
    </div>
    <div class="col-auto">
      <%= f.submit '作成' , class:"btn btn-outline-secondary btn-sm"%>
    </div>
    <% end %>


    <div class="card m-3 p-2">
      <h5>タグ一覧</h5>

      <div class="p-1">
        <% @tags.each do |tag| %>
        <span class="m-1 label-bg d-inline">
          #<%= tag.name %>
          <%= link_to '✖️', admin_tag_path(tag.id), method: :delete, data: { confirm: '削除してよろしいですか？'} %>
        </span>
      <% end %>
    </div>
  </div>
</div>

<%= link_to '管理者画面に戻る', admin_users_path %>
<%= link_to '新しくタスクを投稿する', new_task_path %>

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, @user], local: true) do |f| %>

  <table>
    <tr>
      <td><%= f.label :name, '名前' %></td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td><%= f.label :email, 'メールアドレス' %></td>
      <td><%= f.email_field :email %></td>
    </tr>
    <tr>
      <td><%= f.label :password, 'パスワード' %></td>
      <td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <td><%= f.label :password_confirmation, 'パスワード確認' %></td>
      <td><%= f.password_field :password_confirmation %></td>
    </tr>
    <tr>
      <td><%= f.label :管理者権限 %></td>
      <td><%= f.check_box :admin %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%= f.submit '登録' %></td>
    <tr>
  </table>
<% end %>

app/views/admin/users/edit.html.erb
<h2><%= @user.name %>のページ編集</h2>
<br>
<%= render 'form', user: @user %>

<br>
<br>
<%= link_to "マイページに戻る", user_path(current_user.id) %>
<%= link_to "管理画面に戻る", admin_users_path %>

app/views/admin/users/index.html.erb
<div class="container">
  <h2>Users</h2>


    <table class="table table-hover">
      <br>

    <thead>
    <tr>
      <th>ユーザーID</th>
      <th>ユーザー名</th>
      <th>管理者権限</th>
      <th>タスク数</th>
    </tr>
    </thead>

      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.admin %></td>
          <td>タスク数:<%= user.tasks.count %></td>
          <td>
          <%= link_to '詳細', admin_user_path(user), class: 'btn btn-primary' %>
          <%= link_to '編集', edit_admin_user_path(user.id),class: 'btn btn-info' %>
          <%= link_to '削除', admin_user_path(user), class: 'btn btn-warning', method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

<%= link_to '新規ユーザー登録', new_admin_user_path %>
<%= link_to '新規タグ登録', new_admin_tag_path %>

app/views/admin/users/new.html.erb
<div class="container">
  <%= form_with(model: [:admin, @user], local: true) do |f| %>
    
    <table>
      <tr>
        <td><%= f.label :name, '名前' %></td>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td><%= f.label :email, 'メールアドレス' %></td>
        <td><%= f.email_field :email %></td>
      </tr>
      <tr>
        <td><%= f.label :password, 'パスワード' %></td>
        <td><%= f.password_field :password %></td>
      </tr>
      <tr>
        <td><%= f.label :password_confirmation, 'パスワード確認' %></td>
        <td><%= f.password_field :password_confirmation %></td>
      </tr>
      <tr>
        <td><%= f.label :admin, '管理者' %></td>
        <%= f.hidden_field :admin, value: false %>
        <td><%= f.check_box :admin, {}, true, false %></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><%= f.submit '登録' %></td>
      <tr>
    </table>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<h1>こんにちは<%= @user.name %>さん</h1>
<p>メールアドレス: <%= @user.email %></p>






<table class="table table-hover">
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>終了期限</th>
    <th>ステイタス</th>
    <th>優先順位</th>
    <th>作成者</th>
  </tr>

<% @user.tasks.each do |task| %>
  <tr>
    <td><%= task.title %></td>
    <td><%= task.content %></td>
    <td><%= task.deadline.strftime('%m/%d')%></td>
    <td><%= task.status %></td>
    <td class="sort_priority"><%= task.priority %></td>
    <td><%= task.user.name %></td>
    <td><%= link_to '詳細', task_path(task.id), class: 'btn btn-primary' %></td>
    <td><%= link_to "編集", edit_task_path(task.id), class: 'btn btn-success', data: { confirm: '本当に編集していいですか？' } %></td>
    <td><%= link_to '削除', task_path(task.id), class: 'btn btn-warning', method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>

<%= link_to '新しくタスクを投稿する', new_task_path %>
<%= link_to "終了期限でソートする", tasks_path(sort_expired: "true") %>
<%= link_to "優先順位でソートする", tasks_path(sort_priority: "true") %>
<%= link_to '新規タグ登録', new_admin_tag_path %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to 'Admin', admin_users_path %>
      <%= link_to 'Tasks', tasks_path %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <nav class="navbar navbar-dark bg-primary">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">Task List</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
      </div>

      <div id="gnavi" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <p class="navbar-brand">Task List</p>

        </ul>
      </div>
    </nav>


    <div class="contents">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>



      <%= yield %>

    </div>

  </body>
  <footer>
      <br>
      <br>

      <div id="gnavi" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <p class="navbar-brand">タスク管理株式会社</p>
          <p class="navbar-brand">© 2021 TASK CONTROLL Corp.</p>

        </ul>
      </div>
    </nav>

    </footer>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="task_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="task_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="task_deadline">
    <%= form.label :deadline %>
    <%= form.date_field :deadline %>
  </div>
  <div class="task_status">
    <%= t('form.status') %>
    <%= form.select :status, options_for_select(Task.statuses.keys), {prompt: "選択してください"} %>
  </div>
  <div class="task_priority">
    <%= t('form.priority') %>
    <%= form.select :priority, options_for_select(Task.priorities.keys), {prompt: "選択してください"}  %>
  </div>

  <div class="task_tag">
    <%= form.collection_check_boxes(:tag_ids, Tag.all, :id, :name) %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to "タスク一覧画面にもどる", tasks_path %>

app/views/tasks/edit.html.erb
<h2>タスクを編集する</h2>
 <%= render 'form' %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<p><%= notice %></p>

タスク検索<%= form_with(model: Task.new, method: :get, local: true, url: tasks_path) do |form| %>
<%= form.text_field :title %>
ステータス検索
<%= form.select :status, [["未着手", "0"], ["着手中", "1"], ["完了", "2"]], include_blank: "選択して下さい" %>
<br>
<div class="col-auto">
        <%= form.label :tag, "ラベル", class:"form-label" %>
      </div>
      <div class="col-auto">
        <%= form.select :tag, Tag.all.collect{ |tag| [tag.name, tag.id]}, { include_blank: true } , { class:"form-control form-control-sm status-select" } %>
      <div class="col-auto">
        <%= form.submit '検索' , class:"btn btn-sm btn-outline-secondary" %>
      </div>
      </div>
<% end %>

<table class="table table-hover">
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>終了期限</th>
    <th>ステイタス</th>
    <th>優先順位</th>
    <th>作成者</th>

  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.title %></td>
    <td><%= task.content %></td>
    <td><%= task.deadline.strftime('%m/%d')%></td>
    <td><%= task.status %></td>
    <td class="sort_priority"><%= task.priority %></td>
    <td><%= task.user.name %></td>



    <td><%= link_to '詳細', task_path(task.id), class: 'btn btn-primary' %></td>
    <td><%= link_to "編集", edit_task_path(task.id), class: 'btn btn-success', data: { confirm: '本当に編集していいですか？' } %></td>
    <td><%= link_to '削除', task_path(task.id), class: 'btn btn-warning', method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>

    <td>
      <% task.tags.each do |tag| %>
      <%= tag.name %>
      <% end %>
    </td>
  </tr>

<% end %>

</table>

<%= link_to '新しくタスクを投稿する', new_task_path %>
<%= link_to "終了期限でソートする", tasks_path(sort_expired: "true") %>
<%= link_to "優先順位でソートする", tasks_path(sort_priority: "true") %>
<br>
<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h2>タスクを作成する</h2>
  <%= render 'form' %>

app/views/tasks/show.html.erb
<h1>タスク詳細画面</h1>
<p>タイトル: <%= @task.title %></p>
<p>内容: <%= @task.content %></p>
<p>終了期限: <%= @task.deadline.strftime('%m/%d') %></p>
<p>ステイタス: <%= @task.status %></p>
<p>優先順位: <%= @task.priority %></p>
<p>作成者: <%= @task.user.name %></p>

<td>
  <% @task.tags.each do |tag| %>
  <p>関連タグ#<%= tag.name %></p>
  <% end %>
</td>
<br>
<br>
<%= link_to "タスク一覧画面にもどる", tasks_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name%>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account",class: 'btn btn-info'%>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<h1>こんにちは<%= @user.name %>さん</h1>
<p>メールアドレス: <%= @user.email %></p>

<% if @user == current_user %>
  <%= link_to 'タスクを作成する', new_task_path %>

  <% end %>
</div>


<table class="table table-hover">
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>終了期限</th>
    <th>ステイタス</th>
    <th>優先順位</th>
    <th>作成者</th>
  </tr>

<% @user.tasks.each do |task| %>
  <tr>
    <td><%= task.title %></td>
    <td><%= task.content %></td>
    <td><%= task.deadline.strftime('%m/%d')%></td>
    <td><%= task.status %></td>
    <td class="sort_priority"><%= task.priority %></td>
    <td><%= task.user.name %></td>
    <td><%= link_to '詳細', task_path(task.id), class: 'btn btn-primary' %></td>
    <td><%= link_to "編集", edit_task_path(task.id), class: 'btn btn-success', data: { confirm: '本当に編集していいですか？' } %></td>
    <td><%= link_to '削除', task_path(task.id), class: 'btn btn-warning', method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>

<%= link_to '新しくタスクを投稿する', new_task_path %>
<%= link_to "終了期限でソートする", tasks_path(sort_expired: "true") %>
<%= link_to "優先順位でソートする", tasks_path(sort_priority: "true") %>
<br>